### ISSUE TITLE
Code similarity seems a bit off

### ISSUE THREAD

**Issue by martinkremnicky** [martinkremnicky/ipynb-plagiarism-check#2]
don't have time to check, but it seems like the scores are all comparing the files to the first file, instead or comparing it pair-wise. See screenshot (all columns have the same value)
![image](https://user-images.githubusercontent.com/94135385/229596615-777743d3-352e-4de2-bddc-6a52bd06a498.png)

**Comment by martinkremnicky** [comment]
@oliverweissl

**Comment by oliverweissl** [comment]
will check!

**Comment by oliverweissl** [comment]
seems to be working properly, after checking indexes of code comparisons.
Note: lower triangle cant be masked off since similarity is not symmetric if the compared code snippets have different length.

**Comment by oliverweissl** [comment]
- will investigate with n-gram size for code checker!! could solve the similar scores
